# IF YOU MODIFY THIS FILE, RESTART THE SERVER
# IF YOU MODIFY THIS FILE, RESTART THE SERVER
# IF YOU MODIFY THIS FILE, RESTART THE SERVER

# Site settings
name:        silly graphics
email:       buttface@jackf.me
description: silly.graphics is a growing personal collection of links generally related to graphic design.
url:         https://silly.graphics

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
