
name:        silly graphics
email:       buttface@jackf.me
description:
  alt:       A glorified list of links
  full:      A graphic designer's porn stash.
  br:        A graphic designer's<br> porn stash.
url:         https://silly.graphics
version:     2.7.00

markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile
  - _assets

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
