
name:
  long:      Silly Graphics
  short:     sg
email:       buttface@jackf.me
description: A little collection of links
url:         https://silly.graphics
version:     2.7.00

markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
