
name: Silly Graphics
email: buttface@jackf.me
url: https://silly.graphics
version: 3.2.5
description: >
  Silly Graphics is directory of hyperlinks generally related to graphic design.

markdown: kramdown
permalink: pretty
timezone: Etc/UTC

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore
  - graphics

assets:
  # digest: true

  # currently bugged
  # cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
