
name:        silly graphics
email:       buttface@jackf.me
description:
  full: A graphic designer's porn stash.
  br:   A graphic designer's<br> porn stash.
url:         https://silly.graphics
version:     2.2.02


markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
