
name:        Silly Graphics
email:       buttface@jackf.me
description: Silly Graphics is directory of hyperlinks generally related to graphic design.
url:         https://silly.graphics
version:     3.2.1

markdown: kramdown
permalink: pretty
timezone: Etc/UTC

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore
  - graphics

assets:
  # digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
