
name:        Silly Graphics
email:       buttface@jackf.me
description: Silly Graphics is directory of hyperlinks generally related to graphic design.
url:         https://silly.graphics
version:     2.7.00

markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore
  - arrow.psd
  - icon.psd

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
