
name: Silly Graphics
email: buttface@jackf.me
url: https://silly.graphics
version: 3.5.0
description: >
  Silly Graphics is a growing collection of resources generally pertaining to graphic design.

markdown: kramdown
permalink: pretty
timezone: Etc/UTC

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore
  - graphics

assets:
  # digest: false
  compression: false
  source_maps: false
  sources:
    - "_assets/css"
    - "_assets/js"
